variable "region" {
  description = "The AWS region to deploy to"
  type        = string
  default    = "us-east-1"
}

variable "project_name" {
  description = "The name of the project"
  type        = string
}

variable "environment" {
  description = "Environment name (e.g., dev, prod)"
  type        = string
  default     = "dev"
}

variable "google_client_id" {
  description = <<EOT
Google Client ID for OIDC.
  INSTRUCTIONS:
  1. Go to Google Cloud Console: https://console.cloud.google.com/apis/credentials
  2. Create Credentials > OAuth client ID > Web application.
  3. Name it (e.g., 'Cognito App').
  4. Add 'http://localhost:3000' to Authorized JavaScript origins.
  5. Copy the Client ID and paste it here.
  (Note: You will need to add the Callback URL generated by this module to 'Authorized redirect URIs' AFTER this apply finishes.)
EOT
  type        = string
  sensitive   = true
}

variable "google_client_secret" {
  description = <<EOT
Google Client Secret for OIDC.
  INSTRUCTIONS:
  1. From the same Google Cloud Console credentials page where you got the Client ID.
  2. Copy the Client Secret and paste it here.
EOT
  type        = string
  sensitive   = true
}

variable "callback_urls" {
  description = "List of allowed callback URLs for the identity provider"
  type        = list(string)
  default     = ["http://localhost:3000/api/auth/callback/cognito"]
}

variable "logout_urls" {
  description = "List of allowed logout URLs for the identity provider"
  type        = list(string)
  default     = ["http://localhost:3000"]
}
